### ISSUE TITLE
Docker Compose example

### ISSUE THREAD

**Issue by mancier** [phsmith/rundeck_exporter#26]
Hello Folks!
This is not a real issue, is just an docker-compose example for the exporter

```yaml
version: '3'
services:
  rundeck-exporter:
    image: phsmith/rundeck-exporter:latest
    container_name: rundeck-exporter
    environment:
      RUNDECK_EXPORTER_DEBUG: "False"
      RUNDECK_EXPORTER_HOST: 0.0.0.0 #Default: 127.0.0.1
      RUNDECK_EXPORTER_PORT: 9620
      RUNDECK_URL: https://rundeck.exmample.org
      RUNDECK_TOKEN: 
      RUNDECK_API_VERSION: 31
      RUNDECK_SKIP_SSL: "False"
      RUNDECK_PROJECTS_EXECUTIONS: "True"
      # RUNDECK_PROJECTS_FILTER: "" #space separed
      RUNDECK_PROJECTS_EXECUTIONS_CACHE: "True"
      RUNDECK_CACHED_REQUESTS_TTL: 120
    ports:
    - 9620:9620
```
