### ISSUE TITLE
How we can add multiple targets in Prometheus.yml 

### ISSUE THREAD

**Issue by ganshw** [phsmith/rundeck_exporter#38]
Hi,

We are using Rundeck exporter 2.3.0 and we are running this as a service. we have implemented in nonprod env and want to implement to prod as well.... How we can add two targets using same server IP in Prometheus.yml?

**Comment by phsmith** [comment]
Hi @ganshw,

You can execute the rundeck_exporter specifying different ports with `--port` argument or `RUNDECK_EXPORTER_PORT` environment variable, that way a host could execute multiple instances of the exporter.

**Comment by ganshw** [comment]
I have tried this way...I have added metrics related to rundeck_project_execution and rundeck_system_stats in both nonprod and prod. Prometheus is saying multiple value for these metrics since I am using same metric name. 

Can I try having different naming convention for metrics to get data? What do you suggest?

I have added targets in prometheus.yml this way
- targets: ['Server IP address:9620', 'Server IP address:9621']
9620 is for Nonprod and 9621 is for prod

**Comment by phsmith** [comment]
You can try to do something like:

```
- job_name: 'rundeck-nonprod'
  static_configs:
  - targets: ['Server IP address:9620']

- job_name: 'rundeck-prod'
  static_configs:
  - targets: ['Server IP address:9621']
```
