### ISSUE TITLE
Invalid API Request: /api/41/metrics/metrics

### ISSUE THREAD

**Issue by bryanfang** [phsmith/rundeck_exporter#66]
Hi @phsmith,

thanks a lot for providing the exporter, I am trying to launch a docker container of it with below configuration
```
version: '3'
services:
  rundeck_exporter:
    container_name: rundeck_exporter
    environment:
      RUNDECK_EXPORTER_HOST: 0.0.0.0
      RUNDECK_SKIP_SSL: 'true'
      RUNDECK_TOKEN: QXToken
      RUNDECK_URL: https://rundeckhost
      RUNDECK_PROJECTS_EXECUTIONS: "true"
      RUNDECK_CPU_STATS: "true"
      RUNDECK_MEMORY_STATS: "true"
    image: phsmith/rundeck-exporter:latest
    ports:
    - 9620:9620
```
then got logs from container
{
    "errorCode": "api.error.invalid.request",
    "apiversion": 41,
    "error": true,
    "message": "Invalid API Request: /api/41/metrics/metrics"
}

but when I check system info by using postman:
```
<system>
    <timestamp epoch='1684121125463' unit='ms'>
        <datetime>2023-05-15T03:25:25Z</datetime>
    </timestamp>
    <rundeck>
        <version>4.8.0-20221110</version>
        <build>4.8.0-20221110</build>
        <buildGit>v4.8.0-0-g49731bb</buildGit>
        <node>rundeck</node>
        <base>/home/rundeck</base>
        <apiversion>41</apiversion>
        <serverUUID>a14bc3e6-75e8-4fe4-a90d-a16dcc976bf6</serverUUID>
    </rundeck>
    <executions active='true' executionMode='active' />
    <os>
        <arch>amd64</arch>
        <name>Linux</name>
        <version>4.14.313-235.533.amzn2.x86_64</version>
    </os>
    <jvm>
        <name>OpenJDK 64-Bit Server VM</name>
        <vendor>Ubuntu</vendor>
        <version>11.0.17</version>
        <implementationVersion>11.0.17+8-post-Ubuntu-1ubuntu220.04</implementationVersion>
    </jvm>
    <stats>
        <uptime duration='177567808' unit='ms'>
            <since epoch='1683943557655' unit='ms'>
                <datetime>2023-05-13T02:05:57Z</datetime>
            </since>
        </uptime>
        <cpu>
            <loadAverage unit='percent'>0.05261166449614586</loadAverage>
            <processors>16</processors>
        </cpu>
        <memory unit='byte'>
            <max>32178700288</max>
            <free>2769114336</free>
            <total>3661627392</total>
        </memory>
        <scheduler>
            <running>0</running>
            <threadPoolSize>10</threadPoolSize>
        </scheduler>
        <threads>
            <active>39</active>
        </threads>
    </stats>
    <metrics href='https://rundeckhost/api/41/metrics/metrics?pretty=true' contentType='application/json' />
    <threadDump href='https://rundeckhost/api/41/metrics/threads' contentType='text/plain' />
    <healthcheck href='https://rundeckhost/api/41/metrics/healthcheck' contentType='application/json' />
    <ping href='https://rundeckhost/api/41/metrics/ping' contentType='text/plain' />
</system>
```
please let me know how to fix the problem, thanks!
Best regards,
Bryan
