### ISSUE TITLE
Feature Request: Project node count 

### ISSUE THREAD

**Issue by claudekenni** [phsmith/rundeck_exporter#85]
I think it would be great if we could monitor the node count for certain projects.

This number can be queried by running a request against `GET /api/14/project/[PROJECT]/resources` and then counting the number of entries.

**Comment by phsmith** [comment]
Hi @claudekenni, thanks for using the rundeck_exporter and for your suggestion.
I'll take a look at your request and get back to you soon.

**Comment by phsmith** [comment]
@claudekenni I was thinking about getting the nodes per project and showing them like this:
 
 ```
 # HELP rundeck_project_node_info Rundeck project node info
# TYPE rundeck_project_node_info gauge
rundeck_project_node_info{description="Rundeck server node",hostname="4d6cf9461e16",instance_address="localhost:4440",nodename="4d6cf9461e16",osArch="amd64",osFamily="unix",osName="Linux",osVersion="6.7.8-arch1-1",project_name="test-1"} 1.0
rundeck_project_node_info{description="Rundeck server node",hostname="4d6cf9461e16",instance_address="localhost:4440",nodename="4d6cf9461e16",osArch="amd64",osFamily="unix",osName="Linux",osVersion="6.7.8-arch1-1",project_name="test-2"} 1.0
```

This approach gives you more options for setting up a query to display in your dashboard.
What do you think?

**Comment by claudekenni** [comment]
@phsmith Is this broken down by individual nodes, so each node will have one line in the output?
If so it might be a problem due to us having many nodes and I'm not sure how this would scale with thousands of nodes.

**Comment by phsmith** [comment]
Actually it will be broken down by nodes per project.
But instead of that approach I can do as you suggested first to have a project node counter like:
```
rundeck_project_nodes_total{instance_address="localhost:4440",project_name="test-1"} 2.0
```
How does that sound?

**Comment by claudekenni** [comment]
That sounds great.

**Comment by phsmith** [comment]
All right @claudekenni, new release[ v2.6.5](https://github.com/phsmith/rundeck_exporter/releases/tag/v2.6.5) deployed and available with the new `rundeck_project_nodes_total` metric.

**Comment by claudekenni** [comment]
Awesome thanks.

**Comment by claudekenni** [comment]
Here is the updated ACL Policy needed for this release

```yaml
by:
  username: exporter
description: system:read
for:
  resource:
  - allow:
    - read
    equals:
      kind: system
context:
  application: rundeck
---
by:
  username: exporter
description: project:read
for:
  project:
  - allow:
    - read
    match:
      name: .*
context:
  application: rundeck
---
by:
  username: exporter
description: events:read
for:
  job:
  - allow:
    - view
    - read
context:
  project: .*
---
by:
  username: exporter
description: events:read
for:
  resource:
  - allow:
    - read
    equals:
      kind: event
context:
  project: .*
---
by:
  username: exporter
description: Allow [read] for (All) node
for:
  resource:
  - allow:
    - read
    equals:
      kind: node
context:
  project: .*
```

**Comment by claudekenni** [comment]
This is the extra ACLs I had to add to the Rule

```yaml
---
by:
  username: exporter
description: Allow [read] for node
for:
  node:
  - allow:
    - read
    match:
      nodename: .*
context:
  project: .*

---
by:
  username: exporter
description: Allow [read] for (All) node
for:
  resource:
  - allow:
    - read
    equals:
      kind: node
context:
  project: .*
```
