### ISSUE TITLE
Missing serviceMonitor Template and Port Mismatch in service.yml Template

### ISSUE THREAD

**Issue by naqshava** [phsmith/rundeck_exporter#95]
Hi,

I installed the Helm chart and encountered two issues:

1.The chart doesn't include a serviceMonitor template, requiring users to create it manually after installation.
2.In the service.yml template, the targetPort should match the port. Currently, this discrepancy prevents the pod and service from binding correctly when checking the endpoint in Kubernetes.
Here is the relevant section of the service.yml template:

```yaml
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
```

tnx
